;; AUTO-GENERATED by scripts/build_manual_levels.bb — do not edit by hand.
;; Maps guide chapter id -> level token, from the first chapter-level
;; <!-- level: ... --> marker in each guide .md (source lang). The marker
;; is the single source of truth; regenerate after editing chapter markers:
;;   bb scripts/build_manual_levels.bb

(ns ridley.manual.manual-levels)

(def chapter-levels
  "Chapter id keyword -> level token (\"base\"/\"intermediate\"/\"advanced\")."
  {:ch-01 "base"
   :ch-02 "base"
   :ch-03 "base"
   :ch-04 "base"
   :ch-05 "base"
   :ch-06 "advanced"
   :ch-07 "advanced"
   :ch-08 "intermediate"
   :ch-09 "base"
   :ch-10 "intermediate"
   :ch-11 "advanced"
   :ch-12 "intermediate"
   :ch-13 "intermediate"
   :ch-14 "base"
   :ch-15 "intermediate"
   :ch-16 "base"
   :ch-17 "base"})
