(ns ridley.photogrammetry.accuracy-study-test
  "The gate experiment for `dev-docs/acquisizione-parametrica-design.md`
   (accertamenti 2, 3 and 5).

   Question the design doc asks: 'bastano vanishing point + PnP +
   triangolazione di rette? ... Se l'errore e da decimi di millimetro, v1 e
   fondato.'

   Scenario throughout: the SD-card reader of the scanner-channel Fase 0,
   about 60 x 25 x 10 mm, photographed at ~250 mm with an iPhone main camera
   (4032 x 3024, horizontal FOV 69.4 deg -> f ~ 2900 px). The caliper pins
   ONE dimension (width, sigma 0.02 mm); the reported error is on the other
   two, which is what photogrammetry actually has to deliver.

   Every table printed here is regenerated by `node out/test.js`."
  (:require [cljs.test :refer-macros [deftest is testing]]
            [ridley.photogrammetry.camera :as cam]
            [ridley.photogrammetry.box-fit :as bf]
            [ridley.photogrammetry.synth :as synth]))

(def true-dims [60.0 25.0 10.0])
(def img-w 4032)
(def img-h 3024)
(def fov-deg 69.4)
(def distance 250.0)
(def n-trials 15)

(defn- base-intrinsics [] (cam/intrinsics-from-fov fov-deg img-w img-h))

(defn- fmt [x n]
  (let [s (.toFixed (js/Number. x) n)] s))

(defn- pad [s w]
  (let [s (str s)]
    (str s (apply str (repeat (max 0 (- w (count s))) " ")))))

;; ---------------------------------------------------------------------------
;; One trial

(defn run-trial
  "Run a single synthetic acquisition. Returns per-dimension absolute errors
   (mm) for the two dimensions NOT pinned by the caliper, plus diagnostics."
  [{:keys [seed views sigma-px focal-error true-k1 init-angle init-pos init-dim-frac
           dist]
    :or {sigma-px 0.3 focal-error 0.0 true-k1 0.0
         init-angle 5.0 init-pos 10.0 init-dim-frac 0.20}}]
  (let [r (synth/rng seed)
        dist (or dist distance)
        poses (mapv (fn [[az el]] (synth/viewpoint az el dist)) views)
        n (count poses)
        k-base (base-intrinsics)
        ;; the lens that actually forms the image
        k-true (assoc k-base :k1 true-k1)
        ;; what we BELIEVE about the lens: possibly a wrong focal, and
        ;; (always, in these experiments) no distortion model
        k-assumed (assoc k-base
                         :fx (* (:fx k-base) (+ 1.0 focal-error))
                         :fy (* (:fy k-base) (+ 1.0 focal-error)))
        true-ks (vec (repeat n k-true))
        assumed-ks (vec (repeat n k-assumed))
        obs (synth/observations true-dims poses true-ks sigma-px r)
        init-poses (mapv #(synth/perturb-pose % init-angle init-pos r) poses)
        init-dims (synth/perturb-dims true-dims init-dim-frac r)
        res (bf/fit obs assumed-ks init-dims init-poses
                    {:sigma-px (max 0.05 sigma-px)
                     :scale-constraint {:axis 0 :value (nth true-dims 0) :sigma 0.02}
                     :lm {:max-iterations 200}})
        dims (:dims res)
        ;; the recovered standoff of the first camera, which is where a focal
        ;; error is expected to hide (focal and depth trade off against each
        ;; other under a fixed object size)
        c0 (cam/camera-center (first (:poses res)))
        rec-dist (Math/sqrt (reduce + 0.0 (map * c0 c0)))]
    {:converged? (:converged? res)
     :dims dims
     :n-obs (count obs)
     :err-h (Math/abs (- (nth dims 1) (nth true-dims 1)))
     :err-d (Math/abs (- (nth dims 2) (nth true-dims 2)))
     :cam-dist-rel-err (/ (- rec-dist dist) dist)
     :rms-px (bf/rms-reprojection-px res obs {:sigma-px (max 0.05 sigma-px)})}))

(defn- aggregate
  "RMS and worst-case error over trials, in mm, across both free dimensions."
  [trials]
  (let [errs (mapcat (juxt :err-h :err-d) trials)
        n (count errs)
        rms (Math/sqrt (/ (reduce + 0.0 (map #(* % %) errs)) (max 1 n)))]
    {:rms rms
     :max (apply max errs)
     :rms-px (/ (reduce + 0.0 (map :rms-px trials)) (max 1 (count trials)))
     :cam-dist-rel-err (/ (reduce + 0.0 (map :cam-dist-rel-err trials))
                          (max 1 (count trials)))
     :converged (count (filter :converged? trials))
     :n (count trials)}))

(defn- sweep [label opts-fn values]
  (mapv (fn [v]
          (let [trials (mapv (fn [t] (run-trial (assoc (opts-fn v) :seed (+ 1000 (* 97 t)))))
                             (range n-trials))]
            (assoc (aggregate trials) :value v :label label)))
        values))

(def good-views [[30.0 25.0] [-40.0 20.0] [80.0 40.0]])

;; ---------------------------------------------------------------------------
;; Experiment 1 — edge localisation noise (accertamenti 2 + 5)

(deftest exp-1-noise-sensitivity
  (println "\n=== EXP 1 — dimensional error vs edge localisation noise ===")
  (println "3 views, correct focal, no distortion. Caliper pins width.")
  (println (pad "sigma_px" 10) (pad "RMS err mm" 12) (pad "max err mm" 12)
           (pad "reproj px" 11) "converged")
  (let [rows (sweep :noise (fn [s] {:views good-views :sigma-px s})
                    [0.1 0.3 1.0 3.0 10.0])]
    (doseq [{:keys [value rms max rms-px converged n]} rows]
      (println (pad (fmt value 2) 10) (pad (fmt rms 4) 12) (pad (fmt max 4) 12)
               (pad (fmt rms-px 3) 11) (str converged "/" n)))
    (testing "sub-pixel edge snapping lands in the tenths of a millimetre"
      (let [r (first (filter #(= 0.3 (:value %)) rows))]
        (is (< (:rms r) 0.1)
            (str "at sigma=0.3px expected RMS < 0.1mm, got " (fmt (:rms r) 4)))))
    (testing "error grows about linearly with pixel noise"
      (let [r03 (first (filter #(= 0.3 (:value %)) rows))
            r30 (first (filter #(= 3.0 (:value %)) rows))
            ratio (/ (:rms r30) (:rms r03))]
        (println (str "  -> 10x noise multiplies the error by "
                      (fmt ratio 2) "x"))
        (is (< 3.0 ratio 30.0) "expected roughly linear error growth")))))

;; ---------------------------------------------------------------------------
;; Experiment 2 — focal length error (accertamento 3: does EXIF suffice?)

(deftest exp-2-focal-error
  (println "\n=== EXP 2 — dimensional error vs WRONG focal length ===")
  (println "3 views, sigma 0.3px. Focal misestimated by the given fraction.")
  (println (pad "focal err" 10) (pad "RMS err mm" 12) (pad "max err mm" 12)
           (pad "cam dist err" 13) "converged")
  (let [rows (sweep :focal (fn [e] {:views good-views :sigma-px 0.3 :focal-error e})
                    [0.0 0.005 0.01 0.03 0.10])]
    (doseq [{:keys [value rms max cam-dist-rel-err converged n]} rows]
      (println (pad (str (fmt (* 100 value) 1) "%") 10) (pad (fmt rms 4) 12)
               (pad (fmt max 4) 12)
               (pad (str (fmt (* 100 cam-dist-rel-err) 2) "%") 13)
               (str converged "/" n)))
    (println "  -> the focal error reappears almost entirely as a WRONG CAMERA")
    (println "     DISTANCE, not as wrong dimensions: focal and depth trade off,")
    (println "     and the caliper re-pins the object scale afterwards.")
    (testing "a 1% focal error stays within a tenth of a millimetre"
      (let [r (first (filter #(= 0.01 (:value %)) rows))]
        (is (< (:rms r) 0.3)
            (str "1% focal error gave RMS " (fmt (:rms r) 4) "mm"))))
    (testing "the focal error is genuinely absorbed by the camera distance"
      ;; This is the check that the previous assertion is not a lie of
      ;; omission: if a 10% focal error left NO trace anywhere, the
      ;; experiment would not be exercising the focal at all.
      (let [r (first (filter #(= 0.10 (:value %)) rows))]
        (is (> (Math/abs (:cam-dist-rel-err r)) 0.05)
            (str "expected a ~10% camera-distance error to absorb the focal "
                 "error; got " (fmt (* 100 (:cam-dist-rel-err r)) 2) "%"))))))

;; ---------------------------------------------------------------------------
;; Experiment 3 — number of views and angular baseline

(deftest exp-3-baseline
  (println "\n=== EXP 3 — dimensional error vs view configuration ===")
  (println "sigma 0.3px, correct focal.")
  (println (pad "config" 26) (pad "RMS err mm" 12) (pad "max err mm" 12)
           (pad "cond(JtJ)" 12) "converged")
  (let [configs [["1 view" [[35.0 25.0]]]
                 ["2 views, 15 deg apart" [[35.0 25.0] [50.0 25.0]]]
                 ["2 views, 30 deg apart" [[35.0 25.0] [65.0 25.0]]]
                 ["2 views, 60 deg apart" [[35.0 25.0] [95.0 25.0]]]
                 ["2 views, 90 deg apart" [[35.0 25.0] [125.0 25.0]]]
                 ["3 views, spread" good-views]
                 ["3 views, all face-on" [[0.0 0.0] [1.0 0.5] [-1.0 0.5]]]]]
    (doseq [[name views] configs]
      (let [trials (mapv (fn [t] (run-trial {:views views :sigma-px 0.3
                                             :seed (+ 1000 (* 97 t))}))
                         (range n-trials))
            agg (aggregate trials)
            ;; conditioning of a representative fit
            r (synth/rng 5)
            poses (mapv (fn [[az el]] (synth/viewpoint az el distance)) views)
            ks (vec (repeat (count poses) (base-intrinsics)))
            obs (synth/observations true-dims poses ks 0.0 r)
            res (bf/fit obs ks true-dims poses
                        {:sigma-px 0.3
                         :scale-constraint {:axis 0 :value 60.0 :sigma 0.02}
                         :lm {:max-iterations 3}})
            ev (bf/spectrum res)
            cond-n (/ (first ev) (max 1e-30 (Math/abs (last ev))))]
        (println (pad name 26) (pad (fmt (:rms agg) 4) 12)
                 (pad (fmt (:max agg) 4) 12)
                 (pad (.toExponential (js/Number. cond-n) 1) 12)
                 (str (:converged agg) "/" (:n agg)))))
    (testing "a single view cannot determine the free dimensions"
      (let [one (aggregate (mapv (fn [t] (run-trial {:views [[35.0 25.0]] :sigma-px 0.3
                                                     :seed (+ 1000 (* 97 t))}))
                                 (range n-trials)))
            three (aggregate (mapv (fn [t] (run-trial {:views good-views :sigma-px 0.3
                                                       :seed (+ 1000 (* 97 t))}))
                                   (range n-trials)))]
        (is (> (:rms one) (:rms three))
            "one view should be strictly worse than three")))))

;; ---------------------------------------------------------------------------
;; Experiment 4 — uncorrected lens distortion (accertamento 3, second half)

(deftest exp-4a-distortion-magnitude
  ;; Before asking what distortion COSTS, establish that it is being applied
  ;; at all, and how many pixels it actually moves things. A sweep that shows
  ;; 'no effect' is worthless until this is nailed down.
  (println "\n=== EXP 4a — how many pixels does k1 actually move? ===")
  (println "Displacement of the object's silhouette corners, by distance.")
  (println (pad "distance" 12) (pad "obj width px" 14) (pad "max shift px" 14) "frame frac")
  (doseq [d [250.0 150.0 100.0 60.0]]
    (let [k-base (base-intrinsics)
          k-bent (assoc k-base :k1 -0.10)
          pose (synth/viewpoint 35.0 25.0 d)
          pts (bf/corners true-dims)
          proj-clean (keep #(cam/project k-base pose %) pts)
          proj-bent (keep #(cam/project k-bent pose %) pts)
          shifts (map (fn [[ax ay] [bx by]]
                        (Math/sqrt (+ (* (- ax bx) (- ax bx)) (* (- ay by) (- ay by)))))
                      proj-clean proj-bent)
          xs (map first proj-clean)
          width-px (- (apply max xs) (apply min xs))]
      (println (pad (fmt d 0) 12) (pad (fmt width-px 0) 14)
               (pad (fmt (apply max shifts) 1) 14)
               (str (fmt (* 100 (/ width-px img-w)) 0) "%"))
      (is (> (apply max shifts) 0.0) "distortion must actually displace points")))
  (println "  -> distortion IS applied; at 250mm it is small because the object")
  (println "     sits near the principal point where the radial term is weak."))

(deftest exp-4b-distortion-cost
  (println "\n=== EXP 4b — cost of IGNORING radial distortion, by framing ===")
  (println "3 views, sigma 0.3px. Image formed with k1, solved with k1=0.")
  (println (pad "distance" 10) (pad "true k1" 10) (pad "RMS err mm" 12)
           (pad "max err mm" 12) (pad "reproj px" 11) "converged")
  (doseq [d [250.0 100.0]]
    (doseq [k [0.0 -0.02 -0.05 -0.10]]
      (let [trials (mapv (fn [t] (run-trial {:views good-views :sigma-px 0.3
                                             :true-k1 k :dist d
                                             :seed (+ 1000 (* 97 t))}))
                         (range n-trials))
            agg (aggregate trials)]
        (println (pad (fmt d 0) 10) (pad (fmt k 3) 10) (pad (fmt (:rms agg) 4) 12)
                 (pad (fmt (:max agg) 4) 12) (pad (fmt (:rms-px agg) 3) 11)
                 (str (:converged agg) "/" (:n agg))))))
  (testing "at close framing, ignoring a large k1 measurably hurts"
    (let [clean (aggregate (mapv (fn [t] (run-trial {:views good-views :sigma-px 0.3
                                                     :true-k1 0.0 :dist 100.0
                                                     :seed (+ 1000 (* 97 t))}))
                                 (range n-trials)))
          bent (aggregate (mapv (fn [t] (run-trial {:views good-views :sigma-px 0.3
                                                    :true-k1 -0.10 :dist 100.0
                                                    :seed (+ 1000 (* 97 t))}))
                                (range n-trials)))]
      (println (str "  close framing: clean RMS " (fmt (:rms clean) 4)
                    " mm vs bent RMS " (fmt (:rms bent) 4) " mm"))
      (is (> (:rms bent) (:rms clean))
          "uncorrected distortion should cost something when it is not a pure scale"))))

;; ---------------------------------------------------------------------------
;; Experiment 5 — how good must the hand alignment be? (the v1 UX claim)

(deftest exp-5-initialisation-basin
  (println "\n=== EXP 5 — convergence vs quality of the hand alignment ===")
  (println "3 views, sigma 0.3px. Init pose perturbed by the given angle,")
  (println "position by 10mm, dimensions by 20%.")
  (println (pad "init angle" 12) (pad "RMS err mm" 12) (pad "good fits" 12) "note")
  (doseq [ang [2.0 5.0 10.0 20.0 40.0 60.0 90.0 120.0]]
    (let [trials (mapv (fn [t] (run-trial {:views good-views :sigma-px 0.3
                                           :init-angle ang
                                           :init-pos (* 2.0 ang)
                                           :init-dim-frac 0.4
                                           :seed (+ 1000 (* 97 t))}))
                       (range n-trials))
          ;; a 'good fit' is one that landed on the true optimum, not a
          ;; distant local minimum
          good (filter #(and (< (:err-h %) 0.5) (< (:err-d %) 0.5)) trials)
          agg (aggregate good)]
      (println (pad (str (fmt ang 0) " deg") 12)
               (pad (if (seq good) (fmt (:rms agg) 4) "-") 12)
               (pad (str (count good) "/" n-trials) 12)
               (if (< (count good) n-trials) "some runs fell into a local minimum" ""))))
  (testing "a 5-degree hand alignment reliably converges"
    (let [trials (mapv (fn [t] (run-trial {:views good-views :sigma-px 0.3
                                           :init-angle 5.0 :init-pos 10.0
                                           :seed (+ 1000 (* 97 t))}))
                       (range n-trials))
          good (filter #(and (< (:err-h %) 0.5) (< (:err-d %) 0.5)) trials)]
      (is (>= (count good) (* 0.9 n-trials))
          (str "expected >=90% good fits from a 5 deg init, got "
               (count good) "/" n-trials))))
  (testing "the basin is finite — a wild initialisation does fail"
    ;; Guard against the flat-result trap: if even a 120-degree misalignment
    ;; converged, the perturbation would not be doing anything and the whole
    ;; experiment would be vacuous.
    (let [trials (mapv (fn [t] (run-trial {:views good-views :sigma-px 0.3
                                           :init-angle 120.0 :init-pos 240.0
                                           :init-dim-frac 0.4
                                           :seed (+ 1000 (* 97 t))}))
                       (range n-trials))
          good (filter #(and (< (:err-h %) 0.5) (< (:err-d %) 0.5)) trials)]
      (is (< (count good) n-trials)
          "a 120 deg initialisation should not converge every time"))))

;; ---------------------------------------------------------------------------
;; Experiment 6 — the realistic end-to-end budget

(deftest exp-6-realistic-budget
  (println "\n=== EXP 6 — realistic combined budget ===")
  (println "3 spread views, 0.5px edge snap, 1% focal error, k1=-0.02 ignored,")
  (println "5 deg hand alignment, caliper sigma 0.02mm.")
  (let [trials (mapv (fn [t] (run-trial {:views good-views
                                         :sigma-px 0.5
                                         :focal-error 0.01
                                         :true-k1 -0.02
                                         :init-angle 5.0
                                         :init-pos 10.0
                                         :seed (+ 2000 (* 131 t))}))
                     (range n-trials))
        agg (aggregate trials)]
    (println (str "  RMS error       : " (fmt (:rms agg) 4) " mm"))
    (println (str "  worst case      : " (fmt (:max agg) 4) " mm"))
    (println (str "  reprojection RMS: " (fmt (:rms-px agg) 3) " px"))
    (println (str "  converged       : " (:converged agg) "/" (:n agg)))
    (testing "the combined budget stays inside a quarter of a millimetre"
      (is (< (:rms agg) 0.25)
          (str "combined RMS was " (fmt (:rms agg) 4) "mm")))))
